#define TYPE 1
#define NAME 2
#define TABLE_PREFIX 3
#define PORT 4
#define COLON 5
#define IDENTIFIER 6
#define INTEGER 7
#define INCLUDE 8
#define LESS_THAN 9
#define GREATER_THAN 10
#define INT 11
#define MAIN 12
#define PRINTF 13
#define OP 14
#define CP 15
#define OB 16
#define CB 17
#define KEYWORD 18